title: René Schouten
subtitle: Software and a bit of hardware, science and math
description: >- # this means to ignore newlines until "baseurl:"
  devlopr-jekyll is a beautiful Jekyll Theme Built For Developers, which is optimized for speed and readability.

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "/portofolio" # the subpath of your site, e.g. /blog

# Navigation
urls:
    - text: About
      url: /
    - text: Projects
      url: /blog


# Edit Author details (For multi authors check _data/authors.yml)

author_logo: profilePhoto.jpg
author: René Schouten
author_bio: "
I started developing software at a young age, as a little boy I bought a Lego Mindstorms kit. After some time, I started programming a C like language on the brick. I saw many possibilities, I made a snake game on the little display, a flappy bird game, and I build an automatic 4 on a row game player.

<br/><br/>

These early projects tell something about who I am, I didn’t have example code on how to build the snake game, it was an adventure to find out how to write it. The automatic 4 on a row is not like writing simple consecutive steps, it’s a puzzle to think about what behavior it should have, it required some math and algorithmic thinking. 

<br/><br/>

Over the years, I learned so much more, but the way of thinking is still the same. I like solving puzzles, I like to come up with my own solutions, combining software with hardware, math, and algorithms.
<br/><br/>

I like to work in the field of embedded systems, I have gathered hardware experience by designing PCBs during my study, at home I build a little lab with an oscilloscope, soldering material, a 3d printer and more. I have been working on different embedded platforms, like STM32, Espressif, EmbedOs and Arduino. I often did low level things on register level and I believe that I understand the basic architecture of an ARM like microcontroller well enough.
<br/><br/>

I’m quite ambitious, I like to work on difficult riddles, working towards the point where I build something where I can be proud of. It usually happens that development ends at the point where it just works, I prefer to take it one step further to the level of convenience. 
<br/><br/>

I like to work on all kinds of things: hardware, embedded software, FPGA, software for different kinds of applications or something totally else. I’m looking for that thing that they have in common, the challenging engineering puzzle that needs to be solved.

<br/><br/>"
author_location: Rotterdam, Netherlands
#author_website_url: "url todo"
typewrite-text: The portofolio of René Schouten, embedded software engineer

# Experiences
author_work_experiences:
            - company_name: Nearfield Instruments B.V
              company_logo: NFI.jpg
              company_url: https://www.nearfieldinstruments.com
              designation: Software Engineer
              description: Software at the PLC software team
              visibility: true
            - company_name: TWTG R&D
              company_logo: twtg.png
              company_url: https://twtg.io
              description: I have been contrubuting to the hack the poacher project. This is a non-profit project to help preventing poaching of rhinos using smart poacher detection technology. I have been working on a custom LoRa mesh network for the poacher sniffers.
              designation: Embedded software engineer
              visibility: true
            - company_name: Medical-X
              company_logo: medicalX.jpg
              company_url: https://medical-x.com
              designation: Embedded system engineer
              description: After 2 years of work on production of the NENASim baby simulator, I started developing embedded hardware and software for the ADAM-X patient simulator.
              visibility: true
            - company_name: Medical-X
              company_logo: medicalX.jpg
              company_url: https://medical-x.com
              designation: Production assistant
              description: At Medical-X I have contributed to the production of the NENASim baby simulator.
              visibility: true

# Education
author_education_details:
              - college_logo: HR.jpg
                college_name: Hogeschool Rotterdam
                college_url: https://www.hogeschoolrotterdam.nl
                college_degree: bachelor
                description: Technische informatica / applied computer science
                visibility: true

# Projects
author_project_details:
              - project_thumbnail: debug_flow.jpg
                project_title: Debug Flow
                project_description: A flexible open source log manager
                project_url: /projects/debugflow
                visibility: true
              - project_thumbnail: energymeter.jpg
                project_title: DC energy meter
                project_description: with 700V 16A capabilities
                project_url: /projects/DC-energymeter
                visibility: true
              - project_thumbnail: swarmbotron.jpg
                project_title: Swarmbotron
                project_description: A swarm robotics project
                project_url: /projects/swarmbotron
                visibility: true
              - project_thumbnail: minitron.jpg
                project_title: Minitron
                project_description: an over-enginered ball searching robot
                project_url: /projects/minitron
                visibility: true
              - project_thumbnail: povglobev2.jpg
                project_title: POV Globe V2
                project_description: An improved version of the POV globe
                project_url: /projects/POV-globe-V2
                visibility: true
              - project_thumbnail: povglobe-V1.png
                project_title: POV Globe V1
                project_description: A rotating disk with leds as a round display
                project_url: /projects/POV-globe-V1
                visibility: true
              - project_thumbnail: ufinder.jpg
                project_title: U-Finder
                project_description: A indoor location system with UWB
                project_url: /projects/ufinder
                visibility: true
              - project_thumbnail: bank.png
                project_title: Bank project
                project_description: An ATM with some bad jokes
                project_url: /projects/bank
                visibility: true




# social links
github_username:  r-schouten
linkedin_username: rené-schouten-570949183


#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
#hyvor_talk_website_id: 476

# wakatime username (coding activity)
#wakatime_username: sujaykundu777

# mailchimp embedded form url (newsletter):
#mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# contact form - (choose formspress or getform)
#getform_endpoint: 83b703c3-9e47-4df4-ac55-e24d7eb02abc
#formspree_email: johndoe@gmail.com

# releases - widget can be (sidebar, modal or embed)
olvy_organization: devlopr
olvy_widget_type: sidebar

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-menus
  - jekyll-admin

# Jekyll Admin Config
jekyll_admin:
  # hidden_links:
  #   - posts
  #   - pages
  #   - staticfiles
  #   - datafiles
  #   - configuration
  homepage: "posts"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
