title: René Schouten
subtitle: Software and a bit of hardware, science and math
description: >- # this means to ignore newlines until "baseurl:"
  devlopr-jekyll is a beautiful Jekyll Theme Built For Developers, which is optimized for speed and readability.

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog
permalink: /:title
# Navigation
urls:
    - text: About
      url: /
    - text: Projects
      url: /blog


# Edit Author details (For multi authors check _data/authors.yml)

author_logo: profilePhoto.jpg
author: René Schouten
author_bio: "
Welcome to my portfolio, I’m René Schouten, an enthusiast software developer. I like to solve engineering puzzles, puzzles that need creativity and dedication to be solved. I’m searching for puzzles mainly in the field of embedded systems, where I combine my engineering skills with electronics, algorithms, mathematics. 

<br/><br/>

Over the years I have done numerous projects, on this portfolio you find some projects which I did during my study of applied computer science. I’ve been working on this project with enthusiasm, trying to make something that not just works, but I aimed to make something more convenient and good enough to be proud of it.

<br/><br/>

I have written quite some software for embedded systems, for example on STM32, ESP32, MPS432 ,  Nordic MCUs and ATmega MCUs. I worked with the different platforms, and for some of them I had to do quite some work on register level. For more general software development, I have been using Java and C++ (Qt).  
<br/><br/>

Besides software engineering, I’ve spent quite some time developing hardware. Over the years I have made several PCBs. Gathered the most important tools like an oscilloscope, soldering material, a 3d printer and much more. <br/><br/>


<br/><br/>"
author_location: Rotterdam, Netherlands
#author_website_url: "url todo"
typewrite-text: The portofolio of René Schouten, embedded software engineer

# Experiences
author_work_experiences:
            - company_name: Nearfield Instruments B.V
              company_logo: NFI.jpg
              company_url: https://www.nearfieldinstruments.com
              designation: Software Engineer
              description: Software at the PLC software team
              visibility: true
            - company_name: TWTG R&D
              company_logo: twtg.png
              company_url: https://twtg.io
              description: I have been contrubuting to the hack the poacher project. This is a non-profit project to help preventing poaching of rhinos using smart poacher detection technology. I have been working on a custom LoRa mesh network for the poacher sniffers.
              designation: Embedded software engineer
              visibility: true
            - company_name: Medical-X
              company_logo: medicalX.jpg
              company_url: https://medical-x.com
              designation: Embedded system engineer
              description: After 2 years of work on production of the NENASim baby simulator, I started developing embedded hardware and software for the ADAM-X patient simulator.
              visibility: true
            - company_name: Medical-X
              company_logo: medicalX.jpg
              company_url: https://medical-x.com
              designation: Production assistant
              description: At Medical-X I have contributed to the production of the NENASim baby simulator.
              visibility: true

# Education
author_education_details:
              - college_logo: HR.jpg
                college_name: Hogeschool Rotterdam
                college_url: https://www.hogeschoolrotterdam.nl
                college_degree: bachelor
                description: Technische informatica / applied computer science
                visibility: true

# Projects
author_project_details:
              - project_thumbnail: debug_flow.jpg
                project_title: Debug Flow
                project_description: A flexible open source log manager
                project_url: /projects/debugflow
                visibility: true
              - project_thumbnail: energymeter.jpg
                project_title: DC energy meter
                project_description: with 700V 16A capabilities
                project_url: /projects/DC-energymeter
                visibility: true
              - project_thumbnail: swarmbotron.jpg
                project_title: Swarmbotron
                project_description: A swarm robotics project
                project_url: /projects/swarmbotron
                visibility: true
              - project_thumbnail: minitron.jpg
                project_title: Minitron
                project_description: an over-enginered ball searching robot
                project_url: /projects/minitron
                visibility: true
              - project_thumbnail: povglobev2.jpg
                project_title: POV Globe V2
                project_description: An improved version of the POV globe
                project_url: /projects/POV-globe-V2
                visibility: true
              - project_thumbnail: povglobe-v1.png
                project_title: POV Globe V1
                project_description: A rotating disk with leds as a round display
                project_url: /projects/POV-globe-V1
                visibility: true
              - project_thumbnail: ufinder.jpg
                project_title: U-Finder
                project_description: A indoor location system with UWB
                project_url: /projects/ufinder
                visibility: true
              - project_thumbnail: bank.png
                project_title: Bank project
                project_description: An ATM with some bad jokes
                project_url: /projects/bank
                visibility: true




# social links
github_username:  r-schouten
linkedin_username: rené-schouten-570949183


#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
#hyvor_talk_website_id: 476

# wakatime username (coding activity)
#wakatime_username: sujaykundu777

# mailchimp embedded form url (newsletter):
#mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# contact form - (choose formspress or getform)
#getform_endpoint: 83b703c3-9e47-4df4-ac55-e24d7eb02abc
#formspree_email: johndoe@gmail.com

# releases - widget can be (sidebar, modal or embed)
olvy_organization: devlopr
olvy_widget_type: sidebar

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['opment']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-menus
  - jekyll-admin

# Jekyll Admin Config
jekyll_admin:
  # hidden_links:
  #   - posts
  #   - pages
  #   - staticfiles
  #   - datafiles
  #   - configuration
  homepage: "posts"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
